-- Фикс-раунд ревью Task 2 (сомнение B-6, подтверждённое отдельно): дефолт
-- "720p" в EditProfile.generativeVideoResolution был форматом чужой модели.
--
-- Потребитель поля — генеративный ФОН кадра, это Kling 1.6 t2v/i2v на
-- Replicate (capability text_to_video/image_to_video, ставка $0.045/с — та
-- же, что заложена в смету генеративного видео плана), а не аватарная
-- speech_to_video модель p-video-avatar, у которой формат "720p"/"1080p".
-- Kling принимает разрешение только пиксельной строкой из своих
-- constraints.resolutions; "720p" он не примет вовсе.
--
-- Новая миграция, а не правка применённой: 20260822000000_add_edit_plan уже
-- накатана, контрольная сумма зафиксирована в _prisma_migrations. Данных в
-- EditProfile ни в одной среде, кроме тестовых баз, нет — таблица заведена
-- сегодня той же миграцией, поэтому переносить существующие строки не нужно.
ALTER TABLE "EditProfile" ALTER COLUMN "generativeVideoResolution" SET DEFAULT '1080x1920';
